Controllers/AlunoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVCRazorCRUD.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCRazorCRUD.Controllers
{
    public class AlunoController : Controller
    {
        //[Route("Aluno")]

        Aluno alunoModel = new Aluno();
        public IActionResult Index()
        {
            ViewBag.ListaDeAlunos = alunoModel.ListarAluno();
            return View();
        }

        [Route("Cadastrar")] //para acessar esse > Aluno/Cadastro
        public IActionResult Cadastrar(IFormCollection formulario)
        {
            Aluno aluno = new Aluno();
            //recebe os dados do formulário
            aluno.Nome = formulario["nomeAluno"];
            aluno.Email = formulario["emailAluno"];
            aluno.Endereco = formulario["enderecoAluno"];
            aluno.Telefone = formulario["telefoneAluno"];
            aluno.Escolaridade = formulario["escolaridadeAluno"];

            aluno.CadastrarAluno(aluno);

            return LocalRedirect("/");
        }

        [Route("Atualizar")]
        public IActionResult Atualizar(IFormCollection formulario)
        {
            Aluno aluno = new Aluno();
            //recebe os dados do formulário
            aluno.Id = int.Parse(formulario["idAluno"]);
            aluno.Nome = formulario["nomeAluno"];
            aluno.Email = formulario["emailAluno"];
            aluno.Endereco = formulario["enderecoAluno"];
            aluno.Telefone = formulario["telefoneAluno"];
            aluno.Escolaridade = formulario["escolaridadeAluno"];

            aluno.AtualizarAluno(aluno);

            return LocalRedirect("/");
        }

        [Route("Cadastro")]
        public IActionResult Cadastro()
        {
            return View();
        }

        [Route("~/Aluno/{id}")]
        public IActionResult Remover(int id)
        {
            alunoModel.RemoverAluno(id);

            return LocalRedirect("/Aluno");
        }

        [Route("~/Aluno/Editar/{id}")]
        public IActionResult Editar(int id)
        {
            var listaRetornada = alunoModel.BuscarPorId(id);
            var alunoRetornado = listaRetornada.Find(aluno => aluno.Id == id);

            ViewBag.alunoRetornado = alunoRetornado;

            return View();
        }
    }
}

Controllers/ProfessorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVCRazorCRUD.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCRazorCRUD.Controllers
{
    public class ProfessorController : Controller
    {
        Professor profModel = new Professor();
        public IActionResult Index()
        {
            ViewBag.ListaDeProfessores = profModel.ListarProf();
            return View();
        }

        [Route("~/Professor/Cadastrar")] //para acessar esse > Professor/Cadastro
        public IActionResult Cadastrar(IFormCollection formulario)
        {
            Professor professor = new Professor();
            //recebe os dados do formulário
            professor.Nome = formulario["nomeProf"];
            professor.Email = formulario["emailProf"];
            professor.Endereco = formulario["enderecoProf"];
            professor.Telefone = formulario["telefoneProf"];
            professor.Cargo = formulario["cargoProf"];

            professor.CadastrarProf(professor);

            return LocalRedirect("/");
        }

        [Route("~/Professor/Atualizar")] //para acessar esse > Professor/Cadastro
        public IActionResult Atualizar(IFormCollection formulario)
        {
            Professor professor = new Professor();
            //recebe os dados do formulário
            professor.Id = int.Parse(formulario["idProf"]);
            professor.Nome = formulario["nomeProf"];
            professor.Email = formulario["emailProf"];
            professor.Endereco = formulario["enderecoProf"];
            professor.Telefone = formulario["telefoneProf"];
            professor.Cargo = formulario["cargoProf"];

            professor.AtualizarProf(professor);

            return LocalRedirect("/");
        }

        [Route("~/Professor/Cadastro")]
        public IActionResult Cadastro()
        {
            return View();
        }

        [Route("~/Professor/{id}")]
        public IActionResult Remover(int id)
        {
            profModel.RemoverProf(id);

            return LocalRedirect("/Professor");
        }

        [Route("~/Professor/Editar/{id}")]
        public IActionResult Editar(int id)
        {
            var listaRetornada = profModel.BuscarPorId(id);
            var profRetornado = listaRetornada.Find(professor => professor.Id == id);

            ViewBag.profRetornado = profRetornado;

            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCRazorCRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Escola SENAI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="Index">Alunos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="Cadastro">Cadastrar Alunos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Professor" asp-action="Index">Professor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Professor" asp-action="Cadastro">Cadastrar Professor</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <p>Todos os direitos reservados - C-<strong>410</strong> - Projeto C#</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>